#!/usr/bin/env bash
set -euo pipefail

mkdir -p temp srs

ads_urls=(
  "srs/ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-acfun-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-acfun-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-acfun@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adcolony-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adcolony-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adjust-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adjust-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adobe-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adobe-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adobe@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-alibaba-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-alibaba-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-alibaba@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-amazon-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-amazon-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-amazon@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-applovin-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-applovin-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-atom-data-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-atom-data-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-baidu-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-baidu-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-baidu@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bytedance-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bytedance-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bytedance@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ads-all.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ads-ir.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ai-!cn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ai-chat-!cn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-cas@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-communication@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-companies@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-dev@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ecommerce@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment-cn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-httpdns-cn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-media-cn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-porn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-!cn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-cn@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-speedtest@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-clearbitjs-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-clearbitjs-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-disney@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-dmm-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-dmm-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-dmm@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-duolingo-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-duolingo-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-duolingo@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-emogi-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-emogi-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-facebook-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-facebook-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-flurry-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-flurry-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-fqnovel@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-gamersky@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-growingio-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-growingio-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hetzner@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hiido-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hiido-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hotjar-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hotjar-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hunantv-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hunantv-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hunantv@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-inner-active-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-inner-active-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-instagram-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-instagram-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-instagram@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-iqiyi-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-iqiyi-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-iqiyi@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-jd-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-jd-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-jd@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kuaishou-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kuaishou-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kuaishou@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kugou-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kugou-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kugou@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-le@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-leanplum-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-leanplum-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-letv-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-letv-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-meta-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-meta-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-meta@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-microsoft@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mixpanel-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mixpanel-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mopub-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mopub-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mxplayer-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mxplayer-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-netease-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-netease-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-netease@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-newrelic-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-newrelic-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ogury-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ogury-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-onesignal-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-onesignal-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ookla-speedtest-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ookla-speedtest-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ookla-speedtest@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-openai@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-openx-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-openx-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pikpak@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pixiv@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pocoiq-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pocoiq-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pubmatic-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pubmatic-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pubmatic@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-qihoo360-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-qihoo360-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-qihoo360@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-samsung@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-segment-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-segment-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sensorsdata-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sensorsdata-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sina-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sina-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sina@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-snap@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sohu-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sohu-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sohu@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-speedtest@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-spotify-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-spotify-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-supersonic-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-supersonic-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tagtic-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tagtic-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tappx-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tappx-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-television-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-television-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-uberads-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-uberads-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-umeng-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-umeng-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-umeng@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-unity-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-unity-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-unity@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-verizon@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-whatsapp-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-whatsapp-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-whatsapp@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-wteam-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-wteam-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xhamster-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xhamster-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xhamster@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xiaomi-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xiaomi-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xiaomi@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ximalaya-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ximalaya-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-yahoo-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-yahoo-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-yahoo@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-youku-ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-youku-ads@ads.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-win-spy.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-acfun-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-acfun@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-adcolony-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-adjust-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-adobe-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-adobe@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-alibaba-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-alibaba@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-amazon-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-amazon@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-apple-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-apple@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-applovin-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-atom-data-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-baidu-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-baidu@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bytedance-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bytedance@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-ir.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ai-!cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ai-chat-!cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-cas@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-communication@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-companies@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-dev@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ecommerce@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-entertainment-cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-entertainment@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-httpdns-cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-media-cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-porn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-social-media-!cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-social-media-cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-speedtest@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-clearbitjs-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-disney@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-dmm-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-dmm@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-duolingo-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-duolingo@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-emogi-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-facebook-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-flurry-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-fqnovel@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-gamersky@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-cn@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-growingio-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hetzner@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hiido-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hotjar-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hunantv-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hunantv@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-inner-active-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-instagram-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-instagram@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-iqiyi-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-iqiyi@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-jd-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-jd@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kuaishou-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kuaishou@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kugou-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kugou@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-le@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-leanplum-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-letv-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-meta-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-meta@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-microsoft@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mixpanel-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mopub-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mxplayer-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-netease-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-netease@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-newrelic-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ogury-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-onesignal-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ookla-speedtest-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ookla-speedtest@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-openai@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-openx-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-pikpak@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-pixiv@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-pocoiq-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-pubmatic-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-pubmatic@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-qihoo360-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-qihoo360@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-samsung@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-segment-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sensorsdata-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sina-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sina@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-snap@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sohu-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sohu@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-speedtest@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-spotify-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-supersonic-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tagtic-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tappx-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-television-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-uberads-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-umeng-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-umeng@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-unity-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-unity@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-verizon@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-whatsapp-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-whatsapp@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-wteam-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-xhamster-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-xhamster@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-xiaomi-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-xiaomi@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ximalaya-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-yahoo-ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-yahoo@ads.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-youku-ads.srs"
)
games_cn_urls=(
  "srs/games-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bilibili-game@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bluepoch-games@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-game-accelerator-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-game-platforms-download@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-games-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-games@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-epicgames@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-gamersky.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-herogame.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kurogames@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent-games@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bilibili-game@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bluepoch-games@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-game-accelerator-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-game-platforms-download@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games-!cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-epicgames@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-gamersky.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-herogame.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kurogames@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent-games@cn.srs"
)
games_noncn_urls=(
  "srs/games-noncn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-games-!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-games@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent-games@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent-games@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cygames.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cygames.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-2kgames.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-2kgames.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-wbgames.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-wbgames.srs"
)
games_other_urls=(
  "srs/games-other.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-game-platforms-download.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-games.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-epicgames.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent-games.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-game-platforms-download.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-games.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-epicgames.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent-games.srs"
)
ai_noncn_urls=(
  "srs/ai-noncn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ai-!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ai-chat-!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-doubao@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ai-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ai-chat-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-doubao@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ai-cn@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-openai.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-xai.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google-gemini.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-meta.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-perplexity.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-poe.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-openai.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xai.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google-gemini.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-meta.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-perplexity.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-poe.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-anthropic.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-anthropic.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-jetbrains.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-jetbrains-ai.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-jetbrains.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-jetbrains-ai.srs"
)
ai_cn_urls=(
  "srs/ai-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ai-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-jetbrains@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-deepseek.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ai-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-jetbrains@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-deepseek.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-aixcoder.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-aixcoder.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-apple-intelligence.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple-intelligence.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-doubao.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-doubao.srs"
)
media_urls=(
  "srs/media.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-netflix.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-disney.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-netflix.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-disney.srs"
)
network_cn_urls=(
  "srs/network-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-aws-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-dev-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ntp-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-!cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-china-list.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cloudflare-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-geolocation-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-geolocation-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mihoyo-cn@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-acer@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-adidas@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-adobe@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-aerogard@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-airwick@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-akamai@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-amazon@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-amd@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-amp@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-apple-dev@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-apple-pki@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-apple@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-asus@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-att@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-aws-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-aws@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-azure@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-beats@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bestbuy@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bilibili@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bing@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bluearchive@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bluepoch@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bmw@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-booking@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bridgestone@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-broadcom@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-calgoncarbon@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-canon@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-antivirus@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-automobile-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-bank-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-blog-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-cas@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-collaborate-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-companies@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-cryptocurrency@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-dev-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-dev@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-documents-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ecommerce@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-education-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-electronic-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-enhance-gaming@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-enterprise-query-platform-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-entertainment-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-entertainment@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-finance@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-food-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-hospital-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-httpdns-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-logistics-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-media-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-media@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-mooc-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-netdisk-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-network-security-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ntp-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ntp@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-number-verification-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-outsource-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-remote-control@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-scholar-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-securities-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-social-media-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-speedtest@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-tech-media@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-wiki-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cisco@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-clearasil@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cloudflare-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cloudflare@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-dell@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-dettol@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-digicert@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-duolingo@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-durex@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ebay@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-entrust@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-eset@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-familymart@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-farfetch@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-fflogs@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-finish@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-firebase@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-gigabyte@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-globalsign@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-gog@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google-play@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google-trust-services@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-gucci@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hketgroup@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hm@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hp@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-hsbc-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-huawei-dev@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-huawei@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-icloud@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ifast@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ikea@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-intel@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-itunes@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kaspersky@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kechuang@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-kindle@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-linkedin@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-lysol@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mapbox@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mastercard@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mcdonalds@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-meadjohnson@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-microsoft-dev@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-microsoft-pki@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-microsoft@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mihoyo-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mihoyo@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-miniso@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-mortein@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-movefree@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-msn@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-muji@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-nike@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-nintendo@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-nurofen@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-nvidia@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-okaapps@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-okx@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-openjsfoundation@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-oreilly@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-panasonic@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-paypal@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-pearson@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-primevideo@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-qnap@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-qualcomm@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-razer@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-rb@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-reabble@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-riot@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-samsung@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sectigo@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-shopee@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sky@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sslcom@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-st@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-starbucks@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-steam@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-strepsils@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-swift@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-synology@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-teamviewer@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent-dev@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tesla@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-test-ipv6@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-thelinuxfoundation@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-thetype@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tld-cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tvb@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ubiquiti@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ubisoft@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-vanish@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-veet@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-verizon@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-visa@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-vmware@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-volvo@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-walmart@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-webex@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-westerndigital@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-woolite@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-xbox@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-yahoo@cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-youtube@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-acer@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adidas@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-adobe@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-aerogard@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-airwick@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-akamai@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-amazon@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-amd@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-amp@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple-dev@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple-pki@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-apple@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-asus@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-att@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-aws-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-aws-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-aws@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-azure@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-beats@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bestbuy@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bilibili@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bing@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bluearchive@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bluepoch@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bmw@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-booking@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bridgestone@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-broadcom@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-calgoncarbon@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-canon@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-antivirus@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-automobile-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-bank-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-blog-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-cas@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-collaborate-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-companies@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-cryptocurrency@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-dev-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-dev-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-dev@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-documents-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ecommerce@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-education-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-electronic-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-enhance-gaming@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-enterprise-query-platform-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-finance@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-food-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-hospital-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-httpdns-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-logistics-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-media-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-media@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-mooc-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-netdisk-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-network-security-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ntp-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ntp-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-ntp@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-number-verification-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-outsource-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-remote-control@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-scholar-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-securities-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-!cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-speedtest@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-tech-media@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-wiki-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cisco@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-clearasil@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cloudflare-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cloudflare-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cloudflare@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-dell@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-dettol@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-digicert@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-duolingo@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-durex@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ebay@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-entrust@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-eset@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-familymart@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-farfetch@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-fflogs@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-finish@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-firebase@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-gigabyte@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-globalsign@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-gog@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google-play@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google-trust-services@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-gucci@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hketgroup@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hm@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hp@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-hsbc-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-huawei-dev@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-huawei@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-icloud@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ifast@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ikea@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-intel@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-itunes@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kaspersky@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kechuang@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-kindle@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-linkedin@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-lysol@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mapbox@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mastercard@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mcdonalds@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-meadjohnson@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-microsoft-dev@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-microsoft-pki@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-microsoft@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mihoyo-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mihoyo-cn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mihoyo@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-miniso@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-mortein@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-movefree@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-msn@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-muji@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-nike@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-nintendo@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-nurofen@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-nvidia@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-okaapps@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-okx@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-openjsfoundation@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-oreilly@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-panasonic@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-paypal@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pearson@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-primevideo@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-qnap@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-qualcomm@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-razer@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-rb@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-reabble@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-riot@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-samsung@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sectigo@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-shopee@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sky@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sslcom@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-st@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-starbucks@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-steam@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-strepsils@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-swift@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-synology@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-teamviewer@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent-dev@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tesla@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-test-ipv6@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-thelinuxfoundation@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-thetype@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tld-cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tvb@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ubiquiti@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ubisoft@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-vanish@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-veet@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-verizon@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-visa@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-vmware@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-volvo@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-walmart@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-webex@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-westerndigital@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-woolite@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xbox@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-yahoo@cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-youtube@cn.srs"
)
network_noncn_urls=(
  "srs/network-noncn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-bank-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-dev-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-geolocation-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-gfw.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-win-extra.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-win-update.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-alibaba@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-alibabacloud@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-aliyun@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bilibili@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-boc@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-bytedance@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-browser-!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-companies@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-entertainment@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-pt@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-scholar-!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-social-media-!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-speedtest@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ccb@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-chinamobile@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-chinatelecom@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-chinaunicom@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-citic@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cmb@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ctexcel@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ctrip@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-deepin@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-dewu@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-didi@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-eastmoney@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-google@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-googlefcm@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-huawei@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-huaweicloud@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-icbc@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-ipip@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-iqiyi@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-jd@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-oneplus@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-oppo@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-pingan@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-qcloud@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-sina@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tencent@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tiktok@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-tld-!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-trae@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-vivo@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-xiaomi@!cn.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-zte@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-alibaba@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-alibabacloud@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-aliyun@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bilibili@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-boc@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-bytedance@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-bank-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-browser-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-companies@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-dev-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-entertainment@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-pt@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-scholar-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-social-media-cn@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-category-speedtest@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ccb@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-chinamobile@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-chinatelecom@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-chinaunicom@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-citic@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-cmb@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ctexcel@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ctrip@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-deepin@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-dewu@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-didi@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-eastmoney@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-google@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-googlefcm@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-huawei@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-huaweicloud@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-icbc@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-ipip@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-iqiyi@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-jd@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-oneplus@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-oppo@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-pingan@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-qcloud@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-sina@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tencent@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tiktok@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-tld-!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-trae@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-vivo@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-xiaomi@!cn.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-zte@!cn.srs"
)
git_urls=(
  "srs/git.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-github.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-gitlab.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-github.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-gitlab.srs"
)
private_urls=(
  "srs/private.srs"
  "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-private.srs"
  "https://raw.githubusercontent.com/lyc8503/sing-box-rules/rule-set-geosite/geosite-private.srs"
)

merge_group()
{
  local GROUP_NAME=$1
  shift
  local URLS=("$@")
  local LOCAL_SRS_FILE="${URLS[0]}"
  local TIMESTAMP
  TIMESTAMP=$(date -u +%Y%m%dT%H%M%SZ)

  rm -f temp/input-"$GROUP_NAME"-*.srs

  if [ -f "$LOCAL_SRS_FILE" ] && [ -s "$LOCAL_SRS_FILE" ]; then
    cp "$LOCAL_SRS_FILE" "temp/input-$GROUP_NAME-0.srs"
  else
    echo "Warning: local file $LOCAL_SRS_FILE not found or is empty. Starting fresh."
    mkdir -p "$(dirname "$LOCAL_SRS_FILE")"
  fi

  local i=1
  local pids=()
  for url in "${URLS[@]:1}"; do
    if [ -z "$url" ]; then
      continue
    fi

    local current_i=$i
    (
      local file_index=$current_i
      local output_file="temp/input-$GROUP_NAME-$file_index.srs"
      echo "Downloading $url to $output_file"
      wget -q --timeout=180 --tries=3 "$url" -O "$output_file" \
        || { echo "Warning: failed to download $url (group $GROUP_NAME)"; rm -f "$output_file"; }
    ) &
    pids+=($!)

    ((i++))
  done

  if [ ${#pids[@]} -gt 0 ]; then
    echo "Waiting for ${#pids[@]} downloads for group $GROUP_NAME..."
    wait "${pids[@]}" 2>/dev/null
    echo "Downloads for $GROUP_NAME finished."
  fi

  shopt -s nullglob
  local inputs=(temp/input-"$GROUP_NAME"-*.srs)
  shopt -u nullglob

  if [ "${#inputs[@]}" -eq 0 ]; then
    echo "Error: no input files available for group $GROUP_NAME — skipping merge."
    return 1
  fi

  echo "Found ${#inputs[@]} input files for group $GROUP_NAME"

  local config_file="temp/config-$GROUP_NAME.json"
  cat > "$config_file" << EOF
{
  "version": 1.12.12,
  "rule_set": [
EOF

  local first=true
  for input_file in "${inputs[@]}"; do
    if [ "$first" = true ]; then
      first=false
    else
      echo "," >> "$config_file"
    fi
    local rule_tag="rule_$(basename "$input_file" .srs)"
    local abs_path
    abs_path=$(realpath "$input_file")
    cat >> "$config_file" << EOF
    {
      "tag": "$rule_tag",
      "type": "local",
      "format": "binary",
      "path": "$abs_path"
    }
EOF
  done

  cat >> "$config_file" << EOF
  ]
}
EOF

  echo "Generated config file for $GROUP_NAME with ${#inputs[@]} rule sets"

  echo "Config file preview (first 100 lines):"
  head -100 "$config_file"

  local backup="srs/${GROUP_NAME}.srs.bak.${TIMESTAMP}"
  if [ -f "$LOCAL_SRS_FILE" ]; then
    cp -a "$LOCAL_SRS_FILE" "$backup"
  fi

  echo "Compiling merged rule set for $GROUP_NAME..."
  if sing-box rule-set compile "$config_file" -o "$LOCAL_SRS_FILE"; then
    echo "Successfully compiled $LOCAL_SRS_FILE"
    cp -a "$LOCAL_SRS_FILE" "srs/${GROUP_NAME}.srs"
  else
    echo "Error: Failed to compile rule set for $GROUP_NAME"
    if [ -f "$backup" ]; then
      cp -a "$backup" "$LOCAL_SRS_FILE"
      echo "Restored from backup: $backup"
    fi
    return 1
  fi

  rm -f temp/input-"$GROUP_NAME"-*.srs "$config_file"
  echo "Merged group $GROUP_NAME -> $LOCAL_SRS_FILE (backup: $backup)"
}

merge_group "ads" "${ads_urls[@]}"
merge_group "games-cn" "${games_cn_urls[@]}"
merge_group "games-noncn" "${games_noncn_urls[@]}"
merge_group "games-other" "${games_other_urls[@]}"
merge_group "ai-noncn" "${ai_noncn_urls[@]}"
merge_group "ai-cn" "${ai_cn_urls[@]}"
merge_group "media" "${media_urls[@]}"
merge_group "network-cn" "${network_cn_urls[@]}"
merge_group "network-noncn" "${network_noncn_urls[@]}"
merge_group "git" "${git_urls[@]}"
merge_group "private" "${private_urls[@]}"

# git config --global user.name "GitHub Actions"
# git config --global user.email "actions@github.com"
# git add srs/*.srs
# git commit -m "Daily merge update: $(date +%Y-%m-%d)" || echo "No changes to commit"
# git push origin main

