name: Update IP Blocklists

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  update-list:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: remove old files
      run: |
        mkdir -p ip
        rm -f ip/*.txt

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ip rule processor
      run: python ip/update_tables.py
      
    - name: Commit and push if changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update IP Blocklists"
        file_pattern: "ip/*.txt"
