name: Update IP Blocklists

on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-ip-blocklists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: remove old files
      run: |
        rm -f adguard-ip-blocklist.txt
        rm -f ipv4-list.txt
        rm -f ipv6-list.txt

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install radix requests

    - name: Run IP blocklist update script
      run: python process_ip_lists.py
      
    - name: Commit and push if changed
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "chore: Update IP blocklists"
        file_pattern: "adguard-ip-blocklist.txt ipv4-list.txt ipv6-list.txt README.md"
