name: Update 1024Hosts

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  update-1024hosts:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: remove old files
        run: |
          mkdir -p rules/hosts
          rm -f rules/hosts/1024hosts.txt

      - name: Download and process hosts
        run: |
          # 下载原始文件
          curl -s -L -o temp_rules https://github.com/Goooler/1024_hosts/raw/master/hosts
          # 修改内容并保存到hosts文件夹下的1024hosts.txt
          sed 's/^127\.0\.0\.1/0.0.0.0/g' temp_rules > hosts/1024hosts.txt
          # 清理临时文件
          rm -f temp_rules

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update 1024Hosts"
          file_pattern: "rules/hosts/1024hosts.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
