name: Update Blocklist Daily

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old files
        run: |
          mkdir -p adh
          rm -f adh/*.txt

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install HostlistCompiler
        run: npm install -g @adguard/hostlist-compiler

      - name: Compile blocklist
        run: hostlist-compiler -c adh/config.json -o adh/blocklist.txt

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Blocklist Daily"
          file_pattern: "adh/*.txt"